//priority: 1000
const blacklist = [
    //Mekanism
    'mekanism:ultimate_crushing_factory',
    'mekanism:advanced_sawing_factory', 
    'mekanism:elite_sawing_factory', 
    'mekanism:ultimate_sawing_factory', 
    'mekanism:basic_logistical_transporter',  
    'mekanism:advanced_logistical_transporter',  
    'mekanism:elite_logistical_transporter',  
    'mekanism:ultimate_logistical_transporter',  
    'mekanism:diversion_transporter',  
    'mekanism:basic_smelting_factory',  
    'mekanism:advanced_smelting_factory',  
    'mekanism:elite_smelting_factory',  
    'mekanism:ultimate_smelting_factory',  
    'mekanism:crusher',  
    'mekanism:digital_miner',  
    'mekanism:energized_smelter',  
    'mekanism:precision_sawmill',  
    'mekanism:restrictive_transporter',
    'mekanism:creative_energy_cube',  
    'mekanism:basic_crushing_factory',  
    'mekanism:basic_sawing_factory',  
    'mekanism:advanced_crushing_factory',  
    'mekanism:elite_crushing_factory',
    'mekanism:enriched_iron',
    'mekanism:steel_casing',
    'mekanism:basic_mechanical_pipe',
    'mekanism:advanced_mechanical_pipe',
    'mekanism:elite_mechanical_pipe',
    'mekanism:ultimate_mechanical_pipe',
    'mekanism:basic_fluid_tank',
    'mekanism:advanced_fluid_tank',
    'mekanism:elite_fluid_tank',
    'mekanism:ultimate_fluid_tank',
    'mekanism:creative_fluid_tank',

    //Aquaculture
    'aquaculture:wooden_fillet_knife',
    'aquaculture:stone_fillet_knife',
    'aquaculture:iron_fillet_knife',
    'aquaculture:gold_fillet_knife',
    'aquaculture:diamond_fillet_knife',

    //ae2
    'ae2:vibration_chamber',
    'ae2sky_stone_tank',

    //Create
    'create:powdered_obsidian',

    //Neapolitan
    'neapolitan:chocolate_bar',
    'neapolitan:milk_bottle',

    //Bees
    'productivebees:milk_bottle',

    //Silentgear
    'silentgear:paxel_blueprint',
    'silentgear:paxel_head',
    'silentgear:paxel',
    'silentgear:saw_blueprint',
    'silentgear:saw_head',
    'silentgear:saw',
    'silentgear:blueprint_package',

    //endrem
    'endrem:cold_eye',
    'endrem:nether_eye',
    'endrem:black_eye',

    //scalinghealth
    'scalinghealth:heart_crystal_ore',
    'scalinghealth:power_crystal_ore',
    'scalinghealth:deepslate_heart_crystal_ore',
    'scalinghealth:deepslate_power_crystal_ore',
    'scalinghealth:power_crystal',
    'scalinghealth:power_crystal_shard',
    'scalinghealth:cursed_heart',
    'scalinghealth:enchanted_heart',
    'scalinghealth:chance_heart',

    //twilightforest
    'twilightforest:uncrafting_table',

    //nethersdelight
    'nethersdelight:iron_machete',
    'nethersdelight:golden_machete',
    'nethersdelight:diamond_machete',
    'nethersdelight:netherite_machete',
    
    //progressive bosses
    'progressivebosses:nether_star_shard',

    //gobber2
    'gobber2:gobber2_ore',
    'gobber2:gobber2_ore_deepslate',
    'gobber2:gobber2_ore_nether',
    'gobber2:gobber2_ore_end',
    'gobber2:gobber2_lucky_block',
    'gobber2:gobber2_lucky_block_deepslate',
    'gobber2:gobber2_lucky_block_nether',
    'gobber2:gobber2_lucky_block_end',
    'gobber2:gobber2_helmet',
    'gobber2:gobber2_chestplate',
    'gobber2:gobber2_leggings',
    'gobber2:gobber2_boots',
    'gobber2:gobber2_helmet_nether',
    'gobber2:gobber2_chestplate_nether',
    'gobber2:gobber2_leggings_nether',
    'gobber2:gobber2_boots_nether',
    'gobber2:gobber2_helmet_end',
    'gobber2:gobber2_chestplate_end',
    'gobber2:gobber2_leggings_end',
    'gobber2:gobber2_boots_end',

    // croptopia
    'croptopia:cabbage_roll',
    'croptopia:cooking_pot',
    'croptopia:frying_pan',
    'croptopia:knife',
    'croptopia:rice',
    'croptopia:cabbage_seed',
    'croptopia:tomato_seed',
    'croptopia:onion_seed',
    'croptopia:strawberry_seed',
    'croptopia:vanilla_seeds',
    'croptopia:flour',

    // tarantulas
    'tarantula:antidote',
    'tarantula:emptyantidote',

    // IF
    'industrialforegoing:pitiful_generator',
    'industrialforegoing:bio_reactor',
    'industrialforegoing:mycelial_furnace',
    'industrialforegoing:mycelial_magma',
    'industrialforegoing:mycelial_netherstar',
    'industrialforegoing:plant_gatherer',
    'industrialforegoing:plant_sower',
    'industrialforegoing:animal_rancher',
    'industrialforegoing:mob_crusher',
    'industrialforegoing:mob_duplicator',
    'industrialforegoing:wither_builder',
    'industrialforegoing:resourceful_furnace',
    'industrialforegoing:block_placer',
    'industrialforegoing:block_breaker',
    'industrialforegoing:fluid_collector',
    'industrialforegoing:fluid_placer',
    'industrialforegoing:material_stonework_factory',
    'industrialforegoing:potion_brewer',
    'industrialforegoing:ore_laser_base',
    'industrialforegoing:laser_drill',
    'industrialforegoing:fluid_laser_base',
    'industrialforegoing:washing_factory',
    'industrialforegoing:fermentation_station',
    'industrialforegoing:fluid_sieving_machine',
    'industrialforegoing:enchantment_applicator',
    'industrialforegoing:enchantment_extractor',
    'industrialforegoing:enchantment_factory',
    'industrialforegoing:conveyor',
    'industrialforegoing:conveyor_extraction_upgrade',
    'industrialforegoing:conveyor_insertion_upgrade',
    'industrialforegoing:conveyor_detection_upgrade',
    'industrialforegoing:conveyor_bouncing_upgrade',
    'industrialforegoing:conveyor_dropping_upgrade',
    'industrialforegoing:conveyor_blinking_upgrade',
    'industrialforegoing:conveyor_splitting_upgrade',
    'industrialforegoing:item_transporter_type',
    'industrialforegoing:fluid_transporter_type',
    'industrialforegoing:world_transporter_type',
    'industrialforegoing:laser_lens0',
    'industrialforegoing:laser_lens1',
    'industrialforegoing:laser_lens2',
    'industrialforegoing:laser_lens3',
    'industrialforegoing:laser_lens4',
    'industrialforegoing:laser_lens5',
    'industrialforegoing:laser_lens6',
    'industrialforegoing:laser_lens7',
    'industrialforegoing:laser_lens8'
]