//priority: 1001
const materials = [
    {name: 'bronze', ingredients: [{'tag': 'forge:ingots/bronze'}], dust: [{'item': 'mekanism:dust_bronze'}]},
    {name: 'lapis', ingredients: [{'tag': 'forge:gems/lapis'}], dust: [{'item': 'mekanism:dust_lapis_lazuli'}]},
    {name: 'coal', ingredients: [{'item': 'minecraft:coal'}], dust: [{'item': 'mekanism:dust_coal'}]},
    {name: 'charcoal', ingredients: [{'item': 'minecraft:charcoal'}], dust: [{'item': 'mekanism:dust_charcoal'}]},
    {name: 'quartz', ingredients: [{'item': 'minecraft:quartz'}], dust: [{'item': 'mekanism:dust_quartz'}]},
    {name: 'emerald', ingredients: [{'item': 'minecraft:emerald'}], dust: [{'item': 'mekanism:dust_emerald'}]},
    {name: 'diamond', ingredients: [{'item': 'minecraft:diamond'}], dust: [{'item': 'mekanism:dust_diamond'}]},
    {name: 'netherite', ingredients: [{'tag': 'forge:ingots/netherite'}], dust: [{'item': 'mekanism:dust_netherite'}]},
    {name: 'steel', ingredients: [{'tag': 'forge:ingots/steel'}], dust: [{'item': 'mekanism:dust_steel'}]},
    {name: 'refined_obsidian', ingredients: [{'tag': 'forge:ingots/refined_obsidian'}], dust: [{'item': 'mekanism:dust_refined_obsidian'}]},
    {name: 'fluorite', ingredients: [{'tag': 'forge:gems/fluorite'}], dust: [{'item': 'mekanism:dust_fluorite'}]},
    {name: 'iron', ingredients: [{'tag': 'forge:ingots/iron'}], clump:[{'item': 'mekanism:clump_iron'}], dust: [{'item': 'mekanism:dust_iron'}], dirty_dust:[{'item': 'mekanism:dirty_dust_iron'}]},
    {name: 'gold', ingredients: [{'tag': 'forge:ingots/gold'}], clump:[{'item': 'mekanism:clump_gold'}], dust: [{'item': 'mekanism:dust_gold'}], dirty_dust:[{'item': 'mekanism:dirty_dust_gold'}]},
    {name: 'osmium', ingredients: [{'tag': 'forge:ingots/osmium'}], clump:[{'item': 'mekanism:clump_osmium'}], dust: [{'item': 'mekanism:dust_osmium'}], dirty_dust:[{'item': 'mekanism:dirty_dust_osmium'}]},
    {name: 'copper', ingredients: [{'tag': 'forge:ingots/copper'}], clump:[{'item': 'mekanism:clump_copper'}], dust: [{'item': 'mekanism:dust_copper'}], dirty_dust:[{'item': 'mekanism:dirty_dust_copper'}]},
    {name: 'tin', ingredients: [{'tag': 'forge:ingots/tin'}], clump:[{'item': 'mekanism:clump_tin'}], dust: [{'item': 'mekanism:dust_tin'}], dirty_dust:[{'item': 'mekanism:dirty_dust_tin'}]},
    {name: 'lead', ingredients: [{'tag': 'forge:ingots/lead'}], clump:[{'item': 'mekanism:clump_lead'}], dust: [{'item': 'mekanism:dust_lead'}], dirty_dust:[{'item': 'mekanism:dirty_dust_lead'}]},
    {name: 'uranium', ingredients: [{'tag': 'forge:ingots/uranium'}], clump:[{'item': 'mekanism:clump_uranium'}], dust: [{'item': 'mekanism:dust_uranium'}], dirty_dust:[{'item': 'mekanism:dirty_dust_uranium'}]},
    {name: 'zinc', ingredients: [{'tag': 'forge:ingots/zinc'}], clump:[{'item': 'jaopca:mekanism_clumps.zinc'}], dust: [{'item': 'jaopca:dusts.zinc'}], dirty_dust:[{'item': 'jaopca:mekanism_dirty_dusts.zinc'}]},
    {name: 'pendorite', ingredients: [{'tag': 'forge:ingots/pendorite'}], dust: [{'item': 'jaopca:dusts.pendorite'}]},
    {name: 'knightmetal', ingredients: [{'tag': 'forge:ingots/knightmetal'}], dust: [{'item': 'jaopca:dusts.knightmetal'}]},
    {name: 'ironwood', ingredients: [{'tag': 'forge:ingots/ironwood'}], dust: [{'item': 'jaopca:dusts.ironwood'}]},
    {name: 'crimson_iron', ingredients: [{'tag': 'forge:ingots/crimson_iron'}], clump:[{'item': 'jaopca:mekanism_clumps.crimson_iron'}], dust: [{'item': 'silentgear:crimson_iron_dust'}], dirty_dust:[{'item': 'jaopca:mekanism_dirty_dusts.crimson_iron'}]},
    {name: 'crimson_steel', ingredients: [{'tag': 'forge:ingots/crimson_steel'}], dust: [{'item': 'silentgear:crimson_steel_dust'}]},
    {name: 'blaze_gold', ingredients: [{'tag': 'forge:ingots/blaze_gold'}], dust: [{'item': 'silentgear:blaze_gold_dust'}]},
    {name: 'azure_silver', ingredients: [{'tag': 'forge:ingots/azure_silver'}], clump:[{'item': 'jaopca:mekanism_clumps.azure_silver'}], dust: [{'item': 'silentgear:azure_silver_dust'}], dirty_dust:[{'item': 'jaopca:mekanism_dirty_dusts.azure_silver'}]},
    {name: 'azure_electrum', ingredients: [{'tag': 'forge:ingots/azure_electrum'}], dust: [{'item': 'silentgear:azure_electrum_dust'}]},
    {name: 'tyrian_steel', ingredients: [{'tag': 'forge:ingots/tyrian_steel'}], dust: [{'item': 'silentgear:tyrian_steel_dust'}]},
    {name: 'cloggrum', ingredients: [{'tag': 'forge:ingots/cloggrum'}], clump:[{'item': 'jaopca:mekanism_clumps.cloggrum'}], dust: [{'item': 'jaopca:dusts.cloggrum'}], dirty_dust:[{'item': 'jaopca:mekanism_dirty_dusts.cloggrum'}]},
    {name: 'froststeel', ingredients: [{'tag': 'forge:ingots/froststeel'}], clump:[{'item': 'jaopca:mekanism_clumps.froststeel'}], dust: [{'item': 'jaopca:dusts.froststeel'}], dirty_dust:[{'item': 'jaopca:mekanism_dirty_dusts.froststeel'}]},
    {name: 'regalium', ingredients: [{'tag': 'forge:ingots/regalium'}], dust: [{'item': 'jaopca:dusts.regalium'}]},
    {name: 'utherium', ingredients: [{'tag': 'forge:ingots/utherium'}], dust: [{'item': 'jaopca:dusts.utherium'}]},
];