
[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		mangrove = true
		crimson = true
		warped = true

	[wood_type.quark]
		azalea = true
		blossom = true

	[wood_type.silentgear]
		netherwood = true

	[wood_type.byg]
		aspen = true
		baobab = true
		blue_enchanted = true
		bulbis = true
		cherry = true
		cika = true
		cypress = true
		ebony = true
		ether = true
		fir = true
		green_enchanted = true
		holly = true
		imparius = true
		lament = true
		jacaranda = true
		mahogany = true
		white_mangrove = true
		maple = true
		nightshade = true
		palm = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true
		sythian = true

	[wood_type.twilightforest]
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		time = true
		transformation = true
		mining = true
		sorting = true

	[wood_type.deeperdarker]
		echo = true

	[wood_type.undergarden]
		smogstem = true
		wigglewood = true
		grongle = true

	[wood_type.dreamland]
		plum_birch = true
		tar_bark = true
		mold_wood = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		mangrove = true
		azalea = true
		flowering_azalea = true

	[leaves_type.silentgear]
		netherwood = true

	[leaves_type.byg]
		araucaria = true
		blue_spruce = true
		blooming_witch_hazel = true
		brown_birch = true
		brown_oak = true
		brown_zelkova = true
		flowering_orchard = true
		flowering_palo_verde = true
		holly_berry = true
		indigo_jacaranda = true
		flowering_jacaranda = true
		flowering_indigo_jacaranda = true
		joshua = true
		ripe_joshua = true
		orange_birch = true
		orange_oak = true
		orange_spruce = true
		orchard = true
		palo_verde = true
		pink_cherry = true
		red_birch = true
		red_maple = true
		red_oak = true
		red_spruce = true
		ripe_orchard = true
		silver_maple = true
		green_apple_skyris = true
		white_cherry = true
		yellow_birch = true
		yellow_spruce = true
		withering_oak = true
		flowering_nightshade = true
		firecracker = true
		aspen = true
		baobab = true
		blue_enchanted = true
		cika = true
		cypress = true
		ebony = true
		ether = true
		fir = true
		green_enchanted = true
		holly = true
		lament = true
		jacaranda = true
		mahogany = true
		white_mangrove = true
		maple = true
		nightshade = true
		palm = true
		pine = true
		rainbow_eucalyptus = true
		redwood = true
		skyris = true
		willow = true
		witch_hazel = true
		zelkova = true

	[leaves_type.twilightforest]
		thorn = true
		beanstalk = true
		twilight_oak = true
		canopy = true
		mangrove = true
		dark = true
		rainbow_oak = true
		time = true
		transformation = true
		mining = true
		sorting = true

	[leaves_type.ars_nouveau]
		blue_archwood = true
		red_archwood = true
		green_archwood = true
		purple_archwood = true

	[leaves_type.deeperdarker]
		echo = true

	[leaves_type.undergarden]
		smogstem = true
		wigglewood = true
		grongle = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.ars_elemental]
		yellow_archwood = true

	[leaves_type.dreamland]
		tar_bark = true
		plum_birch = true

