
[General]
	#The chance a Pumpkillager will spawn when a player breaks a pumpkin block.
	#Range: 0.001 ~ 1.0
	pumpkillagerSpawnChance = 0.1
	#Whether the Pumpkillager should spawn when pumpkins are broken while the player is in creative mode.
	enablePumpkillagerSpawnDuringCreative = false
	#The amount of health the final boss should have.
	#Range: 1.0 ~ 10000.0
	finalBossMaxHealth = 300.0
	#How much experience the final boss should drop on death.
	#Range: 0 ~ 10000
	experienceAmountRewardFinalBoss = 250
	#This is a feature to add more pumpkins to the world, to make people come across the Pumpkillager in a more natural way. Whenever a pig spawns, it has a chance to spawn on top of a pumpkin block. This will make them be sprinkled around the world. To turn it off, set the config chance value to 0.
	#Range: 0.0 ~ 1.0
	chanceForPumpkinBlockToSpawnOnPigSpawn = 0.15

