
#General mod settings
[general]
	#Mobs enhanced by zombie awareness
	enhancedMobs = ["minecraft:zombie", "minecraft:husk", "minecraft:zombie_villager", "rottencreatures:burned", "rottencreatures:swampy", "rottencreatures:undead_miner", "rottencreatures:frostbitten"]

