
[Tooltips]
	#Display food properties in tooltips
	"Food Icons" = true
	#Display equipment attributes in tooltips
	"Equipment Icons" = true
	#Display reduced tooltips for new inventory buttons
	"Small Tooltips" = true
	#Range: -1000 ~ 1000
	"Inventory Buttons Offset X" = 0
	#Range: -1000 ~ 1000
	"Inventory Buttons Offset Y" = 0

